---
name: Docs

on:
  push:
    branches: [man-html-pub]

permissions:
  # This workflow pushes to the gh-pages branch, so the token needs write
  # privileges for repo contents.
  contents: write

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    container: registry.ci.openshift.org/coreos/fcos-buildroot:testing-devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # This is taken from ci/travis-install.sh but should probably be
      # refactored.
      - name: Install dependencies
        run: ./ci/installdeps.sh

      - name: Build API docs and manpages
        run: |
          ./autogen.sh --enable-gtk-doc --enable-man --enable-man-html
          make -C apidoc
          make manhtml

      - name: Build and publish jekyll docs
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: docs
          target_branch: gh-pages
          # Only publish when pushing to main.
          # XXX: Maybe this should only run on the release event?
          # build_only: ${{ github.ref == 'refs/heads/main' && 'false' || 'true' }}
          # Run the prep script to put the API docs in place.
          pre_build_commands: ./docs/prep-docs.sh
